### PR TITLE
Upgrade bsp4j and implement buildTarget/javacOptions and fix build/taskFinish

### LINKED ISSUE #988: [BSP] - Missing `build/taskFinish`
A bit related to https://github.com/lihaoyi/mill/issues/987 but also a bit different is that it at the moment Mill doesn't have [compile-notifications](https://build-server-protocol.github.io/docs/specification.html#compile-notifications). I'll quote from this great explanation from Olaf in the Scala Contributors forum.

> compile progress notifications, Metals relies on BSP compile progress notifications (https://build-server-protocol.github.io/docs/specification.html#compile-notifications) in order to know when to update indexes, restart the presentation compiler, display progress bars for the user in the status bar and tree views.

The relevant thread starts [here](https://contributors.scala-lang.org/t/build-server-protocol-in-sbt/4234/17)

So basically we'd expect something like this, which is an example from Bloop:

```
[Trace - 06:03:42 PM] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "3"
  },
  "eventTime": 1603991022406,
  "message": "Compiled \u0027MillTester\u0027",
  "status": 1,
  "dataKind": "compile-report",
  "data": {
    "target": {
      "uri": "file:/Users/ckipp/Documents/scala-workspace/mill-tester/MillTester/?id\u003dMillTester"
    },
    "errors": 0,
    "warnings": 0,
    "isNoOp": true,
    "isLastCycle": true,
    "clientDir": "file:///Users/ckipp/Documents/scala-workspace/mill-tester/.bloop/out/MillTester/bloop-bsp-clients-classes/classes-Metals-oA3DnvH8RFaQprwm5dzvRA\u003d\u003d/",
    "analysisOut": "file:///Users/ckipp/Documents/scala-workspace/mill-tester/.bloop/out/MillTester/MillTester-analysis.bin"
  }
}
```
And as an example, here you can see the progress bar still going, even though the compilation has been finished, but no `buid/taskFinish` received.

Screenshot 2020-10-29 at 18 09 58

### LINKED ISSUE #1024: BSP failing on Intellij with buildTarget/javacOptions not implemented
Sounds like we need to implement buildTarget/javacOptions

### PR DESCRIPTION
**Pull request by joan38**
Fixes #1024 and fixes #988

### CODE REVIEW

File: scalalib/worker/src/ZincWorkerImpl.scala [hunk 1]
```diff
@@ -411,6 +411,11 @@ class ZincWorkerImpl(compilerBridge: Either[
           r.logInfo(new ZincProblem(problem))
           super.logInfo(problem)
         }
+
+        override def printSummary(): Unit = {
+          r.printSummary()
+          super.printSummary()
+        }
```
Comment (joan38) [inline scalalib/worker/src/ZincWorkerImpl.scala:418]: That the override that was missing to trigger the finish compilation notification

File: bsp/src/mill/bsp/MillBuildServer.scala [hunk 2]
```diff
@@ -393,7 +412,7 @@ class MillBuildServer(evaluator: Evaluator, bspVersion: String, serverVersion: S
                     .dest / "classes").toNIO.toUri.toString
 
                   Some(new ScalacOptionsItem(targetId, options.asJava, classpath.iterator.toSeq.asJava, classDirectory))
-                case _: JavaModule => None
+                case _ => None
```
Comment (joan38) [inline bsp/src/mill/bsp/MillBuildServer.scala:415]: Any other types should be skipped

File: bsp/src/mill/bsp/MillBuildServer.scala [hunk 3]
```diff
@@ -361,6 +336,50 @@ class MillBuildServer(evaluator: Evaluator, bspVersion: String, serverVersion: S
       new CleanCacheResult(msg, cleaned)
     }
 
+  override def workspaceReload(): CompletableFuture[Object] =
+    handleExceptions {
+      BSP.install(evaluator)
```
Comment (joan38) [inline bsp/src/mill/bsp/MillBuildServer.scala:341]: This seem far from sufficient and would effectively implemented with a redesign of how we run BSP outside of a task command.

**Comment by joan38** [comment]
@lefou I'm going to merge this now since I got people who upgraded to Intellij 2020.3 and mill BSP doesn't work anymore. But please feel free to comment on this PR and I can address them in a separate PR.

File: bsp/src/mill/bsp/MillBuildServer.scala (hunk 3 above)
Comment (ckipp01) [reply bsp/src/mill/bsp/MillBuildServer.scala:341]: Just in case it was an oversight, this will never get hit by a client. Without having 
```scala
capabilities.setCanReload(true)
```
in the `buildInitialize` clients probably won't event attempt to trigger this since right now the field is absent, so the assumption is that it's not implemented.

Comment (joan38) [reply bsp/src/mill/bsp/MillBuildServer.scala:341]: Thanks for pointing this out @ckipp01 I was not aware of this.

**Comment by Iltotore** [comment]
Hello, after compiling Mill from this PR, [I still have this problem](https://youtrack.jetbrains.com/issue/SCL-18519). Are you sure it is solved now ?

**Comment by joan38** [comment]
@Iltotore try `0.9.3-17-3f8afc`. We publish all master commits.

**Comment by Iltotore** [comment]
Hello, in my last comment I meant I already compiled and local-released mill + reinstalling BSP in a fresh empty project. This error still happens.

**Comment by joan38** [comment]
@Iltotore have you tried `0.9.3-17-3f8afc` as I mentioned above? Is it working?

**Comment by Iltotore** [comment]
Hello @joan38 , I finally tested today and I still get the same problem. Feel free to ping me here or on gitter
